/**
 * Live preview of a camera move, rendered as a CSS transform on a still.
 *
 * Higgsfield ships a rendered video clip per preset. We cannot reuse theirs —
 * those are their copyrighted creative works — and generating 25 of our own
 * costs real money and has to be redone whenever a preset is retuned.
 *
 * A camera move, though, is a *transform*, not content. Applying the actual
 * motion to a still says what the preset does more clearly than a video does,
 * because it isolates the move from whatever happened to be in frame. It also
 * costs nothing, works offline, and cannot drift out of sync with the preset.
 *
 * The tradeoff is honest: this shows the geometry of the move, not the look of
 * the output. Presets that are about *content* rather than motion (the VFX
 * families) will need real rendered previews — generated by us.
 */

import { presetPreview } from "../mock";

/**
 * Slug → animation. Anything unmapped falls back to a slow push, which reads
 * as "some camera move" rather than as a specific wrong one.
 *
 * Signs are from the camera's point of view: panning right moves the *frame*
 * right, so the image travels left.
 */
const MOVE_CLASS: Record<string, string> = {
  "push-in": "cam-push-in",
  "dolly-in": "cam-push-in",
  "zoom-in": "cam-zoom-in",
  "push-out": "cam-push-out",
  "dolly-out": "cam-push-out",
  "zoom-out": "cam-zoom-out",
  "pan-right": "cam-pan-right",
  "pan-left": "cam-pan-left",
  "tilt-up": "cam-tilt-up",
  "tilt-down": "cam-tilt-down",
  "crane-up": "cam-crane-up",
  "crane-down": "cam-crane-down",
  "aerial-pullback": "cam-aerial-pullback",
  "tracking-shot": "cam-tracking",
  "drone-orbit": "cam-orbit",
  "360-orbit": "cam-orbit-full",
  "arc-left": "cam-arc-left",
  "arc-right": "cam-arc-right",
  "bullet-time": "cam-bullet-time",
  handheld: "cam-handheld",
  "pov-walk": "cam-pov-walk",
  "rack-focus": "cam-rack-focus",
  "dolly-zoom": "cam-dolly-zoom",
  "dolly-zoom-in": "cam-dolly-zoom-in",
  // Deliberately no animation: a locked-off shot that drifted would be a lie
  // about what the preset does.
  "static-shot": "cam-static",
};

export function cameraClass(slug: string): string {
  return MOVE_CLASS[slug] ?? "cam-push-in";
}

export function CameraPreview({
  slug,
  src,
  active,
}: {
  slug: string;
  /** Optional real frame; falls back to the generated gradient. */
  src?: string;
  /** Hover/focus state, lifted so the whole card can drive it. */
  active: boolean;
}) {
  return (
    <span className="cam-frame" data-active={active}>
      <img
        className={`cam-plate ${cameraClass(slug)}`}
        src={src ?? presetPreview(slug)}
        alt=""
        draggable={false}
      />
    </span>
  );
}
