import { useMemo, useRef, useState } from "react";
import type { Model, PresetFamily } from "../types";
import {
  availableCategories,
  filterPresets,
  pagePresets,
} from "../lib/presets";
import { selectVariant } from "../lib/variants";
import { isPlayableUrl } from "../lib/media";
import { CameraPreview } from "./CameraPreview";
import { presetPreview } from "../mock";
import { Overlay } from "./Overlay";
import { EmptyState } from "./EmptyState";
import { SearchIcon } from "./Icons";

const PAGE = 12;

/** A clip when we have one, otherwise the move played as a CSS transform.
 *
 * Camera presets get the transform path by default and are better for it: the
 * motion is exactly what the preset controls, and showing it on a neutral
 * plate isolates the move from whatever a rendered clip happened to contain.
 * Rendered previews stay supported for the content-driven families, where
 * geometry says nothing useful — those have to be generated by us. */
function PresetCard({
  preset,
  modelId,
  onPick,
}: {
  preset: PresetFamily;
  modelId: string | null;
  onPick: () => void;
}) {
  const videoRef = useRef<HTMLVideoElement>(null);
  const [hot, setHot] = useState(false);
  const variant = selectVariant(preset, modelId);
  const src = variant?.previewUrl ?? presetPreview(preset.id);
  const playable = isPlayableUrl(src);
  const asMove = !playable && preset.category === "camera-control";

  return (
    <button
      type="button"
      className="preset-card"
      onClick={onPick}
      onMouseEnter={() => {
        setHot(true);
        void videoRef.current?.play().catch(() => {});
      }}
      onMouseLeave={() => {
        setHot(false);
        videoRef.current?.pause();
      }}
      onFocus={() => setHot(true)}
      onBlur={() => setHot(false)}
      aria-label={`Use preset ${preset.displayName}`}
    >
      {playable ? (
        <video
          ref={videoRef}
          className="preset-card-media"
          src={src}
          loop
          muted
          playsInline
          preload="none"
        />
      ) : asMove ? (
        <CameraPreview slug={preset.id} src={src} active={hot} />
      ) : (
        <img className="preset-card-media" src={src} alt="" />
      )}
      <span className="media-bevel" aria-hidden="true" />
      <span className="preset-card-caption">
        <span className="preset-card-name">
          {preset.displayName.toUpperCase()}
        </span>
        <span className="preset-card-category">{preset.category}</span>
      </span>
    </button>
  );
}

export function PresetPicker({
  open,
  onClose,
  presets,
  models,
  activeModelId,
  onPick,
}: {
  open: boolean;
  onClose: () => void;
  presets: PresetFamily[];
  models: Model[];
  activeModelId: string | null;
  onPick: (preset: PresetFamily) => void;
}) {
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("All");
  const [modelFilter, setModelFilter] = useState<string | null>(activeModelId);
  const [shown, setShown] = useState(PAGE);

  const categories = useMemo(() => availableCategories(presets), [presets]);
  const filtered = useMemo(
    () =>
      filterPresets(presets, {
        query,
        category,
        modelId: modelFilter ?? undefined,
      }),
    [presets, query, category, modelFilter],
  );
  const { page, remaining } = pagePresets(filtered, shown);

  const reset = (fn: () => void) => {
    fn();
    setShown(PAGE);
  };

  const videoModels = models.filter((m) => m.modality === "video");

  return (
    <Overlay
      open={open}
      onClose={onClose}
      title="Presets"
      variant="full"
      header={
        <div className="overlay-search">
          <SearchIcon size={16} />
          <label className="sr-only" htmlFor="preset-search">
            Search presets
          </label>
          <input
            id="preset-search"
            type="search"
            placeholder="Search presets"
            value={query}
            onChange={(e) => reset(() => setQuery(e.currentTarget.value))}
          />
        </div>
      }
    >
      <div className="picker-filters">
        <div className="tabs tabs-inline" role="tablist" aria-label="Model">
          <button
            type="button"
            role="tab"
            className="tabs-tab"
            aria-selected={modelFilter === null}
            onClick={() => reset(() => setModelFilter(null))}
          >
            All models
          </button>
          {videoModels.map((m) => (
            <button
              key={m.id}
              type="button"
              role="tab"
              className="tabs-tab"
              aria-selected={modelFilter === m.id}
              onClick={() => reset(() => setModelFilter(m.id))}
            >
              {m.displayName}
            </button>
          ))}
        </div>

        <div className="chip-filters" role="group" aria-label="Category">
          {categories.map((c) => (
            <button
              key={c}
              type="button"
              className="chip chip-button"
              aria-pressed={category === c}
              onClick={() => reset(() => setCategory(c))}
            >
              {c}
            </button>
          ))}
        </div>
      </div>

      {page.length === 0 ? (
        <EmptyState
          heading="No presets match"
          explanation="Nothing in this category matches that search. Clear the filters to see the full catalog."
          action={
            <button
              type="button"
              className="btn btn-primary"
              onClick={() =>
                reset(() => {
                  setQuery("");
                  setCategory("All");
                  setModelFilter(null);
                })
              }
            >
              Clear filters
            </button>
          }
        />
      ) : (
        <>
          <div className="preset-grid">
            {page.map((preset) => (
              <PresetCard
                key={preset.id}
                preset={preset}
                modelId={modelFilter ?? activeModelId}
                onPick={() => {
                  onPick(preset);
                  onClose();
                }}
              />
            ))}
          </div>
          {remaining > 0 ? (
            <div className="picker-more">
              <button
                type="button"
                className="btn btn-outline"
                onClick={() => setShown((s) => s + PAGE)}
              >
                Load more ({remaining})
              </button>
            </div>
          ) : null}
        </>
      )}
    </Overlay>
  );
}
